### ISSUE TITLE
MelonDS permits non-normalized bone weights on models when hardware does not

### ISSUE THREAD

**Issue by BromBromBromley** [melonDS-emu/melonDS#2242]
As the title states, something I ran into while testing a project I was working on is that a rigged NSBMD I had created is that while it would work OK on MelonDS, when I tried using it on hardware, it always appeared to softlock. I realized that some vertices didn't have a sum of 1.0 for their weights, and as a result, it didn't function properly on hardware. Upon making sure my weighting was normalized, it then worked, but regardless of the legality of my weights, MelonDS permitted it.

**Comment by Arisotura** [comment]
It's weird because I'd expect this sort of calculation to be done in software. It'd be interesting to have more details as to why non-normalized bone weights are failing on hardware.

**Comment by BromBromBromley** [comment]
I'm a little uncertain on the best way to provide additional details with hardware. I did at least discover that with EveryFileExplorer, its NSBMD settings viewer can be used as a diagnostic at least in terms of seeing if something is malformed. It threw this exception here:
For some reason, the model *does* work on MelonDS despite it generally being accurate. I also have the exception log from EFE as well here:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NDS.GPU.CommandContext.RestoreMatrix(UInt32 index)
   at NDS.GPU.CommandContext.RunDL(Byte[] DL)
   at NDS.NitroSystem.G3D.SBC.Execute()
   at NDS.UI.MDL0Viewer.Render()
   at NDS.UI.MDL0Viewer.MDL0Viewer_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at NDS.UI.NSBMDViewer.treeView1_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
If you wanted to see the area the stacktrace was referring to, it can be found [here](https://github.com/PabloMK7/EveryFileExplorer/blob/43c08c11af58567f06a7118bb9af88ba74e810ba/NDS/GPU/CommandContext.cs#L204)

**Comment by Arisotura** [comment]
would be interesting to have a test ROM along with malformed files and good ones, so I could test this, but I also offer no guarantee

however, that stack trace gives a bit of insight -- something about the matrix restore command? it's weird, because I thought I had fixed the matrix stack stuff to mirror hardware behavior, but maybe there are odd edge cases I wasn't aware of.

**Comment by BromBromBromley** [comment]
Would it be possible for me to send the problematic files through any sort of private message?

**Comment by Arisotura** [comment]
you can contact me over Discord or IRC, or on the forums

https://melonds.kuribo64.net/board/

**Comment by Jaklyy** [comment]
my instinct is it could be the gx hanging, or some quirk related to partially gx command submission.
i know those two things aren't handled properly in melonDS as of now

**Comment by BromBromBromley** [comment]
I see! Thanks for the insight!
